import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import CartProvider from "@/lib/CartContext";
import NetworkStatus from "@/components/layout/NetworkListener";
import { ClerkProvider } from "@clerk/nextjs";
// import { Head } from "next/document";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <head>
          {/* <Head> */}
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-2FD2N2NPM3"></script>
            <script
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){window.dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', 'G-2FD2N2NPM3');
                `,
              }}
            />
          {/* </Head> */}
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CartProvider>
              <div className="mb-2">
                <NetworkStatus />
              </div>
            {children}
            <Toaster />
          </CartProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
